spring.application.name=worker
spring.datasource.url=jdbc:postgresql://localhost:5432/flowforge
spring.datasource.username=flowforge
spring.datasource.password=flowforge_dev
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=flowforge
spring.rabbitmq.password=flowforge_dev

spring.server.port=8081
spring.jpa.open-in-view=false