spring.application.name=worker
spring.datasource.url=jdbc:postgresql://localhost:5432/flowforge
spring.datasource.username=flowforge
spring.datasource.password=flowforge_dev
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=flowforge
spring.rabbitmq.password=flowforge_dev

spring.server.port=8081
spring.jpa.open-in-view=false


# Flowforge processor
flowforge.processor.path=/opt/flowforge/processor

# Resilience4j retry
resilience4j.retry.instances.stepExecution.max-attempts=3
resilience4j.retry.instances.stepExecution.wait-duration=1s
resilience4j.retry.instances.stepExecution.retry-exceptions[0]=java.io.IOException
resilience4j.retry.instances.stepExecution.retry-exceptions[1]=java.net.http.HttpTimeoutException
resilience4j.retry.instances.stepExecution.retry-exceptions[2]=java.lang.RuntimeException
resilience4j.retry.instances.stepExecution.ignore-exceptions[0]=java.lang.IllegalArgumentException
resilience4j.retry.instances.stepExecution.ignore-exceptions[1]=java.lang.UnsupportedOperationException

# Logging
logging.level.root=INFO
logging.level.com.flowforge.worker=DEBUG
logging.level.org.springframework=WARN
logging.level.org.hibernate=WARN